services:
  - type: web
    name: namelees-visual
    runtime: python
    buildCommand: ""
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
